services:
  project-management-db:
    image: postgres:16
    container_name: project-management-db
    volumes:
      - project_management_pgdata:/var/lib/postgresql/data
    env_file:
      - .db.prod.env
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - app_net

  project-management-backend:
    build:
      context: ./backend
    container_name: project-management-backend
    env_file:
      - .backend.prod.env
    depends_on:
      - project-management-db
    ports:
      - "8000:8000"
    networks:
      - app_net

  project-management-frontend:
    build:
      context: ./frontend
    container_name: project-management-frontend
    depends_on:
      - project-management-backend
    ports:
      - "3000:3000"
    networks:
      - app_net

volumes:
  project_management_pgdata:

networks:
  app_net:
    driver: bridge
