services:
  project-management-db:
    image: postgres:16
    container_name: project-management-db
    volumes:
      - project_management_pgdata:/var/lib/postgresql/data
    env_file:
      - .db.env
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  project_management_pgdata:
